-- =============================================================================
-- 167 Guild Wiki — Initial Group Seed
-- =============================================================================
--
-- Purpose:
--   Create the initial Wiki.js permission groups for the 167 Guild Wiki.
--
-- Groups created:
--   - Dungeon Master  (full campaign management, including /dm/ namespace)
--   - Player          (participant access; denied /dm/ namespace)
--   - Viewer          (read-only; denied /dm/ namespace)
--
-- Note on Platform Administrator:
--   Wiki.js ships with a built-in "Administrators" system group (isSystem = true).
--   Platform Administrators should be assigned to that built-in group through the
--   Wiki.js Admin UI. Do not attempt to recreate or replace the Administrators
--   system group here.
--
-- Note on Anonymous access:
--   Wiki.js ships with a built-in "Guests" system group.
--   Leave its permissions empty to deny all anonymous access by default.
--
-- Usage:
--   Run this script AFTER Wiki.js has completed its first boot and initialized
--   its database schema.
--
--   From the host:
--     docker compose exec -T postgres psql \
--       -U wikijs -d wikidb \
--       < scripts/bootstrap/seed-groups.sql
--
--   This script is idempotent: it skips creation if a group with the same name
--   already exists.
--
-- Schema reference:
--   Wiki.js 2.x — table: groups
--   Column names are camelCase as generated by the Knex.js ORM migrations.
--   Permissions and pageRules are stored as JSON text.
--
-- Verify column names against your installed Wiki.js version by running:
--   \d groups
--
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Dungeon Master
--
-- Full campaign management access.
-- May read and write all content, including the /dm/ hidden namespace.
-- -----------------------------------------------------------------------------
INSERT INTO groups (
    name,
    "isSystem",
    permissions,
    "pageRules",
    "redirectOnLogin"
)
SELECT
    'Dungeon Master',
    FALSE,
    '["read:pages","write:pages","manage:pages","delete:pages","read:assets","write:assets","manage:assets","read:comments","write:comments","manage:comments","read:source"]',
    '[
      {
        "id":    "dm-allow-all",
        "roles": ["read:pages","write:pages","manage:pages","delete:pages","read:assets","write:assets","manage:assets"],
        "match": "START",
        "deny":  false,
        "path":  "/",
        "locales": []
      }
    ]',
    '/'
WHERE NOT EXISTS (
    SELECT 1 FROM groups WHERE name = 'Dungeon Master'
);

-- -----------------------------------------------------------------------------
-- Player
--
-- Campaign participant access.
-- May read all public content, write own character pages and session journals.
-- Explicitly denied access to the /dm/ namespace.
--
-- Page rules are evaluated in order:
--   1. Deny read and write on /dm/ (DM-only content).
--   2. Allow read on / (all published content).
--   3. Allow write on /characters/ (own character pages).
--   4. Allow write on /journals/ (session journals).
--
-- Note: Wiki.js does not enforce per-user page ownership natively.
-- The write rules below grant write access to all Players within the
-- /characters/ and /journals/ namespaces. Fine-grained ownership is deferred.
-- -----------------------------------------------------------------------------
INSERT INTO groups (
    name,
    "isSystem",
    permissions,
    "pageRules",
    "redirectOnLogin"
)
SELECT
    'Player',
    FALSE,
    '["read:pages","write:pages","read:assets","write:assets","read:comments","write:comments"]',
    '[
      {
        "id":    "player-deny-dm",
        "roles": ["read:pages","write:pages","read:assets","write:assets"],
        "match": "START",
        "deny":  true,
        "path":  "/dm/",
        "locales": []
      },
      {
        "id":    "player-allow-read-all",
        "roles": ["read:pages","read:assets"],
        "match": "START",
        "deny":  false,
        "path":  "/",
        "locales": []
      },
      {
        "id":    "player-allow-write-characters",
        "roles": ["write:pages"],
        "match": "START",
        "deny":  false,
        "path":  "/characters/",
        "locales": []
      },
      {
        "id":    "player-allow-write-journals",
        "roles": ["write:pages"],
        "match": "START",
        "deny":  false,
        "path":  "/journals/",
        "locales": []
      }
    ]',
    '/'
WHERE NOT EXISTS (
    SELECT 1 FROM groups WHERE name = 'Player'
);

-- -----------------------------------------------------------------------------
-- Viewer
--
-- Read-only access to all public content.
-- Explicitly denied access to the /dm/ namespace.
-- -----------------------------------------------------------------------------
INSERT INTO groups (
    name,
    "isSystem",
    permissions,
    "pageRules",
    "redirectOnLogin"
)
SELECT
    'Viewer',
    FALSE,
    '["read:pages","read:assets","read:comments"]',
    '[
      {
        "id":    "viewer-deny-dm",
        "roles": ["read:pages","read:assets"],
        "match": "START",
        "deny":  true,
        "path":  "/dm/",
        "locales": []
      },
      {
        "id":    "viewer-allow-read-all",
        "roles": ["read:pages","read:assets"],
        "match": "START",
        "deny":  false,
        "path":  "/",
        "locales": []
      }
    ]',
    '/'
WHERE NOT EXISTS (
    SELECT 1 FROM groups WHERE name = 'Viewer'
);

-- =============================================================================
-- Post-seed instructions
-- =============================================================================
--
-- After running this seed:
--
-- 1. Open the Wiki.js Admin panel.
-- 2. Navigate to Admin → Users.
-- 3. Assign users to their groups (see docs/authorization.md for details).
--
-- Initial group assignments:
--
--   Platform Administrator:
--     - Alan (szmyty@gmail.com) → Administrators (built-in system group)
--
--   Dungeon Master:
--     - Mitchell (placeholder-dm@gmail.com) → Dungeon Master
--       Replace placeholder-dm@gmail.com with Mitchell's actual Google account.
--
--   Player:
--     - Alan/Starwhisper (szmyty@gmail.com) → Player
--     - Kevin (placeholder-kevin@gmail.com) → Player
--       Replace with Kevin's actual Google account.
--     - Christian (placeholder-christian@gmail.com) → Player
--       Replace with Christian's actual Google account.
--     - Tom (placeholder-tom@gmail.com) → Player
--       Replace with Tom's actual Google account.
--
-- See docs/authorization.md for the full onboarding process.
-- =============================================================================
